name: imokay
description: Everything will be just fine.

publish_to: 'none'

version: 2.2.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  adaptive_theme: ^3.2.0
  flutter_vector_icons: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  fluttertoast: ^8.2.1
  shared_preferences: ^2.1.0
  settings_ui: ^2.0.2
  smooth_page_indicator: ^1.1.0
  flex_color_picker: ^3.2.2
  flutter_font_picker: ^1.2.0
  timer_count_down: ^2.2.2
  flutter_riverpod: ^2.3.6
  provider: ^6.0.5
  flutter_local_notifications: ^14.0.1
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  confirm_dialog: ^1.0.1
  lottie: ^2.3.2
  file_picker: ^5.3.0
  pull_down_button: ^0.9.1
  google_nav_bar: ^5.0.6
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  flutter_awesome_select: ^6.5.0
  flutter_launcher_icons: ^0.13.1
  metaballs: ^1.5.0
  slider_controller: ^0.0.5
  google_fonts: ^4.0.4
  iconify_flutter: ^0.0.5
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # Assets
  assets:

    # Audio
    - assets/audio/

    # Icons
    - assets/icons/

    # Animations
    - assets/animations/

    # Text
    - assets/text/
